#!/bin/sh

# Executed by the command interpreter for login shells

# source bashrc
if [ -n "${BASH_VERSION}" ]; then
	if [ -f "${HOME}/.bashrc" ]; then
		# shellcheck source=/dev/null
		. "${HOME}/.bashrc"
	fi
fi

# add local and go specific binaries
export PATH="${HOME}/.local/bin:/usr/local/go/bin:${PATH}"

# set up SSH authentication using GPG keys
GPG_TTY=$(tty)
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

unset SSH_AGENT_PID
export GPG_TTY
export SSH_AUTH_SOCK

# set up dotnet
export DOTNET_CLI_TELEMETRY_OPTOUT=true
export PATH="${HOME}/.dotnet/tools:${PATH}"
